openapi: "3.0.3"
info:
  title: pictures-share-api
  version: "1.0.0"
servers:
  - url: http://localhost:3000
paths:
  "/api/signup":
    post:
      summary: ユーザー登録
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                password:
                  type: string
      responses:
        "201":
          description: "OK"
          headers:
            Set-cookie:
              schema:
                type: string
                example: sessionId=729c9a0c-5b56-499f-2f06-5940ecef8348; Max-Age=86400; Path=/; Domain=localhost; SameSite=Strict; HttpOnly
        "400":
          description: "Bad Request"
        "500":
          description: "Internal Server Error"
    
  "/api/signin":
    post:
      summary: ログイン
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                email:
                  type: string
                password:
                  type: string
      responses:
        "200":
          description: "OK"
          headers:
            Set-cookie:
              schema:
                type: string
                example: sessionId=729c9a0c-5b56-499f-2f06-5940ecef8348; Max-Age=86400; Path=/; Domain=localhost; SameSite=Strict; HttpOnly
        "400":
          description: "Bad Request"
        "500":
          description: "Internal Server Error"

  "/api/users/{userId}":
    get:
      summary: ユーザー情報取得
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                type: object
                properties:
                  userName:
                    type: string
                  email:
                    type: string
                  planId:
                    type: integer
        "400":
          description: "Bad Request"
        "500":
          description: "Internal Server Error"
    post:
      summary: ユーザー情報更新
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                name:
                  type: string
                email:
                  type: string
                password:
                  type: string
      responses:
        "200":
          description: "OK"
        "400":
          description: "Bad Request"
        "500":
          description: "Internal Server Error"
    
  "/api/posts":
    post:
      summary: 画像投稿
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                pictureData:
                  type: string
                tags:
                  type: array
                  items:
                    type: string
      responses:
        "201":
          description: "OK"
        "400":
          description: "Bad Request"
        "500":
          description: "Internal Server Error"

  "/api/posts/public":
    get:
      summary: 公開画像一覧取得
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                type: object
                properties:
                  posts:
                    type: array
                    items:
                      type: object
                      properties:
                        pictureData:
                          type: string
                        tags:
                          type: array
                          items:
                            type: string
                        userId:
                          type: string
                        createdAt:
                          type: string
        "400":
          description: "Bad Request"
        "500":
          description: "Internal Server Error"

  "/api/users/{userId}/posts":
    get:
      summary: 自分の画像一覧取得
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                type: object
                properties:
                  posts:
                    type: array
                    items:
                      type: object
                      properties:
                        pictureData:
                          type: string
                        tags:
                          type: array
                          items:
                            type: string
                        createdAt:
                          type: string
        "400":
          description: "Bad Request"
        "500":
          description: "Internal Server Error"

  "/api/users/{userId}/posts?tags={tags}":
    get:
      summary: タグ検索
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
        - name: tags
          in: query
          required: true
          schema:
            type: string
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                type: object
                properties:
                  posts:
                    type: array
                    items:
                      type: object
                      properties:
                        pictureData:
                          type: string
                        tags:
                          type: array
                          items:
                            type: string
                        createdAt:
                          type: string
        "400":
          description: "Bad Request"
        "500":
          description: "Internal Server Error"

  "/api/users/{userId}/posts?since={since}&until={until}":
    get:
      summary: 日付検索
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
        - name: since
          in: query
          required: true
          schema:
            type: string
        - name: until
          in: query
          required: true
          schema:
            type: string
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                type: object
                properties:
                  posts:
                    type: array
                    items:
                      type: object
                      properties:
                        pictureData:
                          type: string
                        tags:
                          type: array
                          items:
                            type: string
                        createdAt:
                          type: string
        "400":
          description: "Bad Request"
        "500":
          description: "Internal Server Error"

  "/api/users/{userId}/teams":
    get:
      summary: チーム一覧取得
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                type: object
                properties:
                  teams:
                    type: array
                    items:
                      type: object
                      properties:
                        teamId:
                          type: string
                        teamName:
                          type: string
        "400":
          description: "Bad Request"
        "500":
          description: "Internal Server Error"

  "/api/teams/{teamId}/posts":
    get:
      summary: チーム画像一覧取得
      parameters:
        - name: teamId
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                type: object
                properties:
                  posts:
                    type: array
                    items:
                      type: object
                      properties:
                        pictureData:
                          type: string
                        tags:
                          type: array
                          items:
                            type: string
                        createdAt:
                          type: string
        "400":
          description: "Bad Request"
        "500":
          description: "Internal Server Error"

  "/api/teams/{teamId}/users":
    post:
      summary: チーム参加
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                teamId:
                  type: string
                email:
                  type: string
      responses:
        "200":
          description: "OK"
        "400":
          description: "Bad Request"
        "500":
          description: "Internal Server Error"

    delete:
      summary: チーム退会
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                teamId:
                  type: string
                email:
                  type: string
      responses:
        "200":
          description: "OK"
        "400":
          description: "Bad Request"
        "500":
          description: "Internal Server Error"

  "/api/teams":
    post:
      summary: チーム作成
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                teamName:
                  type: string
                userId:
                  type: string
                teamInfo:
                  type: array
                  items: 
                    type: object
                    properties:
                      email:
                        type: string
                      role:
                        type: string
                    
      responses:
        "200":
          description: "OK"
        "400":
          description: "Bad Request"
        "500":
          description: "Internal Server Error"

  "/api/plans":
    put:
      summary: プラン変更
      requestBody:
        required: true
        content:
          application/x-www-form-urlencoded:
            schema:
              type: object
              properties:
                userId:
                  type: string
                planId:
                  type: integer
      responses:
        "200":
          description: "OK"
        "400":
          description: "Bad Request"
        "500":
          description: "Internal Server Error"
