version: "3.9"

services:
  db:
    image: mysql:8.0
    user: mysql
    platform: linux/amd64
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: pictures_share
      TZ: "Asia/Tokyo"
    volumes:
      - ./mysql_data:/var/lib/mysql:rw